name: Test Push

on:
  - push
  - delete

jobs:
  test-push:
    name: testing push

    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - run: |
          echo "ref: ${{github.ref}}"
          echo $GITHUB_EVENT_PATH
          cat $GITHUB_EVENT_PATH
          env
        name: Pushed something...
